// ui/src/routes/inference/+page.svelte
<script lang="ts">
	import JobQueue from "$lib/components/JobQueue.svelte";
	import CreateJobButton from "$lib/components/CreateJobButton.svelte";
	import { setHeaderActions } from "$lib/stores/headerActions";
	import { onDestroy } from "svelte";

	onDestroy(() => setHeaderActions([]));
	setHeaderActions([
		{ component: CreateJobButton, props: { jobType: "inference" } },
	]);
</script>

<JobQueue jobType="inference" />

// apps/fastvideo_studio/src/app/inference/page.tsx
'use client';

import CreateJobButton from '@/components/CreateJobButton';
import { HeaderActions } from '@/components/HeaderActionsContext';
import JobQueue from '@/components/JobQueue';

export default function InferencePage() {
  return (
    <>
      <HeaderActions>
        <CreateJobButton jobType="inference" />
      </HeaderActions>
      <JobQueue jobType="inference" />
    </>
  );
}
