// ui/src/lib/components/SecondarySidebar.svelte
<script lang="ts">
	import type { Job } from "$lib/types";
	import { getJobLogs, downloadJobLog } from "$lib/api";
	import { resizable } from "$lib/actions/resizable";

	let { job, onClose, onWidthChange }: {
		job: Job;
		onClose: () => void;
		onWidthChange?: (w: number) => void;
	} = $props();

	const SIDEBAR_MIN_WIDTH = 280;
	const SIDEBAR_MAX_WIDTH = 750;

	let width = $state(360);
	let isDragging = $state(false);
	let isLoading = $state(false);
	let logs = $state<string[]>([]);
	let logAfter = $state(0);
	let consoleEl: HTMLPreElement;
	let previousJobId = $state<string | null>(null);
	let previousStatus = $state<string | null>(null);
	const stateRef = { logs: [] as string[], logAfter: 0 };
	let pollingLock = false;

	$effect(() => {
		onWidthChange?.(width);
	});

	$effect(() => {
		const wasTerminal =
			previousStatus === "failed" ||
			previousStatus === "stopped" ||
			previousStatus === "completed";
		const isRestarting =
			previousJobId === job.id &&
			wasTerminal &&
			(job.status === "pending" || job.status === "running");

		if (previousJobId !== job.id || isRestarting) {
			logs = [];
			logAfter = 0;
			stateRef.logs = [];
			stateRef.logAfter = 0;
		}
		previousJobId = job.id;
		previousStatus = job.status;
	});

	$effect(() => {
		const shouldPoll = job.status === "running" || job.status === "pending";
		let pollInterval: ReturnType<typeof setInterval> | null = null;
		let mounted = true;

		async function pollLogs() {
			if (!mounted || pollingLock) return;
			pollingLock = true;
			try {
				const logData = await getJobLogs(job.id, stateRef.logAfter);
				if (mounted && logData.lines.length > 0) {
					stateRef.logs = [...stateRef.logs, ...logData.lines];
					stateRef.logAfter = logData.total;
					logs = stateRef.logs;
					logAfter = stateRef.logAfter;
					if (consoleEl) consoleEl.scrollTop = consoleEl.scrollHeight;
				}
			} catch (e) {
				console.error("Failed to fetch logs:", e);
			} finally {
				pollingLock = false;
			}
		}

		pollLogs();
		if (shouldPoll) pollInterval = setInterval(pollLogs, 2000);

		return () => {
			mounted = false;
			if (pollInterval) clearInterval(pollInterval);
		};
	});

	const resizableOpts = $derived({
		edge: "right" as const,
		minWidth: SIDEBAR_MIN_WIDTH,
		maxWidth: SIDEBAR_MAX_WIDTH,
		getWidth: () => width,
		onWidth: (w: number) => (width = w),
		onDragChange: (dragging: boolean) => (isDragging = dragging),
	});

	async function handleDownloadLog(e: MouseEvent) {
		e.preventDefault();
		if (isLoading) return;
		isLoading = true;
		try {
			const blob = await downloadJobLog(job.id);
			const url = window.URL.createObjectURL(blob);
			const a = document.createElement("a");
			a.href = url;
			a.download = `job_${job.id}.log`;
			document.body.appendChild(a);
			a.click();
			window.URL.revokeObjectURL(url);
			document.body.removeChild(a);
		} catch (err) {
			console.error("Failed to download log:", err);
			alert(err instanceof Error ? err.message : "Failed to download log");
		} finally {
			isLoading = false;
		}
	}
</script>

<aside class="sidebar" style="width: {width}px; max-width: {SIDEBAR_MAX_WIDTH}px">
	<div class="header">
		<h2 class="title">Job Details</h2>
		<div class="headerActions">
			<button
				class="btn btnSmall"
				onclick={handleDownloadLog}
				disabled={isLoading || !job.log_file_path}
				title="Download log file"
			>
				Download Log
			</button>
			<button type="button" class="closeBtn" onclick={onClose} title="Close">
				<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
					<path d="M18 6L6 18M6 6l12 12" />
				</svg>
			</button>
		</div>
	</div>
	<div class="consoleSection">
		<div class="consoleHeader">
			<span class="consoleTitle">Console Output</span>
			{#if job.status === "running"}
				<span class="consoleStatus">● Live</span>
			{/if}
		</div>
		<pre bind:this={consoleEl} class="consoleOutput">
			{#if logs.length === 0}
				<span class="consoleEmpty">
					{job.status === "running" ? "Waiting for logs..." : "No logs available"}
				</span>
			{:else}
				{logs.join("\n")}
			{/if}
		</pre>
	</div>
	<div
		class="resizeHandle"
		class:resizeHandleActive={isDragging}
		use:resizable={resizableOpts}
		role="presentation"
	></div>
</aside>

<style>
	.sidebar {
		position: fixed;
		top: var(--header-height);
		right: 0;
		bottom: 0;
		display: flex;
		flex-direction: column;
		max-height: calc(100vh - var(--header-height));
		min-width: 280px;
		background: var(--surface);
		border-left: 1px solid var(--border);
		flex-shrink: 0;
		z-index: 50;
	}
	.resizeHandle {
		position: absolute;
		top: 0;
		left: 0;
		width: 6px;
		bottom: 0;
		cursor: col-resize;
		z-index: 1;
	}
	.resizeHandle:hover,
	.resizeHandleActive {
		background: rgba(99, 102, 241, 0.2);
	}
	.resizeHandle::after {
		content: "";
		position: absolute;
		top: 50%;
		left: 50%;
		transform: translate(-50%, -50%);
		width: 2px;
		height: 24px;
		background: var(--border);
		border-radius: 1px;
		opacity: 0;
		transition: opacity 0.15s;
	}
	.resizeHandle:hover::after,
	.resizeHandleActive::after {
		opacity: 1;
	}
	.header {
		display: flex;
		justify-content: space-between;
		align-items: center;
		padding: 1rem 1.25rem;
		border-bottom: 1px solid var(--border);
		flex-shrink: 0;
	}
	.title {
		font-size: 1rem;
		font-weight: 600;
		margin: 0;
		color: var(--text);
	}
	.headerActions {
		display: flex;
		align-items: center;
		gap: 0.5rem;
	}
	.closeBtn {
		display: flex;
		align-items: center;
		justify-content: center;
		padding: 0.4rem;
		background: none;
		border: none;
		color: var(--text-dim);
		cursor: pointer;
		border-radius: var(--radius);
		transition: color 0.15s, background 0.15s;
	}
	.closeBtn:hover {
		color: var(--text);
		background: rgba(99, 102, 241, 0.08);
	}
	.closeBtn svg {
		width: 18px;
		height: 18px;
	}
	.consoleSection {
		flex: 1;
		display: flex;
		flex-direction: column;
		min-height: 0;
		padding: 1rem 1.25rem;
	}
	.consoleHeader {
		display: flex;
		justify-content: space-between;
		align-items: center;
		margin-bottom: 0.5rem;
	}
	.consoleTitle {
		font-size: 0.8rem;
		font-weight: 600;
		color: var(--text-dim);
		text-transform: uppercase;
		letter-spacing: 0.04em;
	}
	.consoleStatus {
		font-size: 0.7rem;
		color: var(--green);
		font-weight: 500;
	}
	.consoleOutput {
		flex: 1;
		min-height: 0;
		background: var(--bg);
		border: 1px solid var(--border);
		border-radius: var(--radius);
		padding: 0.75rem;
		font-family: Monaco, Menlo, "Ubuntu Mono", Consolas, monospace;
		font-size: 0.75rem;
		line-height: 1.5;
		color: var(--text);
		overflow-y: auto;
		overflow-x: auto;
		white-space: pre-wrap;
		word-wrap: break-word;
		margin: 0;
	}
	.consoleEmpty {
		color: var(--text-dim);
		font-style: italic;
	}
	.btn {
		cursor: pointer;
		border: none;
		border-radius: var(--radius);
		font-family: inherit;
		font-weight: 600;
		font-size: 0.85rem;
		padding: 0.55rem 1.2rem;
		transition: background 0.15s, opacity 0.15s;
	}
	.btn:disabled {
		opacity: 0.5;
		cursor: not-allowed;
	}
	.btnSmall {
		background: transparent;
		color: var(--accent-h);
		border: 1px solid var(--border);
		padding: 0.3rem 0.7rem;
		font-size: 0.8rem;
	}
	.btnSmall:hover {
		background: var(--border);
	}
</style>

// apps/fastvideo_studio/src/components/SecondarySidebar.tsx
'use client';

import * as React from 'react';
import { X } from 'lucide-react';

import { Button } from '@/components/ui/button';
import { useResizable } from '@/hooks/useResizable';
import { downloadJobLog, getJobLogs } from '@/lib/api';
import type { Job } from '@/lib/types';
import { cn } from '@/lib/utils';

const SIDEBAR_MIN_WIDTH = 280;
const SIDEBAR_MAX_WIDTH = 750;
const POLL_INTERVAL_MS = 2000;

export default function SecondarySidebar({
  job,
  onClose,
  onWidthChange,
}: {
  job: Job;
  onClose: () => void;
  onWidthChange?: (w: number) => void;
}) {
  const [width, setWidth] = React.useState(360);
  const [isDragging, setIsDragging] = React.useState(false);
  const [isLoading, setIsLoading] = React.useState(false);
  const [logs, setLogs] = React.useState<string[]>([]);

  // Race-guard refs (mirror the Svelte original): the cursor + accumulated
  // lines live here so in-flight polls don't read stale React state, and
  // pollingLock prevents overlapping fetches. Do NOT swap these for effect
  // deps — they must update synchronously, outside React's render cycle.
  const stateRef = React.useRef<{ logs: string[]; logAfter: number }>({
    logs: [],
    logAfter: 0,
  });
  const pollingLock = React.useRef(false);
  const previousJobId = React.useRef<string | null>(null);
  const previousStatus = React.useRef<string | null>(null);
  const consoleRef = React.useRef<HTMLPreElement | null>(null);

  const { onMouseDown } = useResizable({
    // Right-docked panel with the drag handle on its left edge: dragging the
    // handle left must grow the panel, which is `edge: 'right'` (matches the
    // Svelte original). `edge: 'left'` would invert the drag.
    edge: 'right',
    minWidth: SIDEBAR_MIN_WIDTH,
    maxWidth: SIDEBAR_MAX_WIDTH,
    getWidth: () => width,
    onWidth: setWidth,
    onDragChange: setIsDragging,
  });

  React.useEffect(() => {
    onWidthChange?.(width);
  }, [width, onWidthChange]);

  // Auto-scroll the console to the bottom whenever new lines land. Runs after
  // commit so scrollHeight reflects the freshly-rendered output.
  React.useEffect(() => {
    const el = consoleRef.current;
    if (el) el.scrollTop = el.scrollHeight;
  }, [logs]);

  // Reset on job switch or restart. Declared before the polling effect so the
  // cursor is cleared before the next poll reads it.
  React.useEffect(() => {
    const wasTerminal =
      previousStatus.current === 'failed' ||
      previousStatus.current === 'stopped' ||
      previousStatus.current === 'completed';
    const isRestarting =
      previousJobId.current === job.id &&
      wasTerminal &&
      (job.status === 'pending' || job.status === 'running');

    if (previousJobId.current !== job.id || isRestarting) {
      stateRef.current.logs = [];
      stateRef.current.logAfter = 0;
      setLogs([]);
    }
    previousJobId.current = job.id;
    previousStatus.current = job.status;
  }, [job.id, job.status]);

  React.useEffect(() => {
    const shouldPoll = job.status === 'running' || job.status === 'pending';
    let pollInterval: ReturnType<typeof setInterval> | null = null;
    let mounted = true;

    async function pollLogs() {
      if (!mounted || pollingLock.current) return;
      pollingLock.current = true;
      try {
        const logData = await getJobLogs(job.id, stateRef.current.logAfter);
        if (mounted && logData.lines.length > 0) {
          stateRef.current.logs = [...stateRef.current.logs, ...logData.lines];
          stateRef.current.logAfter = logData.total;
          setLogs(stateRef.current.logs);
        }
      } catch (e) {
        console.error('Failed to fetch logs:', e);
      } finally {
        pollingLock.current = false;
      }
    }

    pollLogs();
    if (shouldPoll) pollInterval = setInterval(pollLogs, POLL_INTERVAL_MS);

    return () => {
      mounted = false;
      if (pollInterval) clearInterval(pollInterval);
    };
  }, [job.id, job.status]);

  async function handleDownloadLog() {
    if (isLoading) return;
    setIsLoading(true);
    try {
      const blob = await downloadJobLog(job.id);
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `job_${job.id}.log`;
      document.body.appendChild(a);
      a.click();
      window.URL.revokeObjectURL(url);
      document.body.removeChild(a);
    } catch (err) {
      console.error('Failed to download log:', err);
      alert(err instanceof Error ? err.message : 'Failed to download log');
    } finally {
      setIsLoading(false);
    }
  }

  return (
    <aside
      className="fixed bottom-0 right-0 top-[var(--header-height)] z-50 flex max-h-[calc(100vh-var(--header-height))] min-w-[280px] shrink-0 flex-col border-l border-border bg-card"
      style={{ width, maxWidth: SIDEBAR_MAX_WIDTH }}
    >
      <div className="flex items-center justify-between border-b border-border px-5 py-4">
        <h2 className="m-0 text-base font-semibold text-foreground">
          Job Details
        </h2>
        <div className="flex items-center gap-2">
          <Button
            type="button"
            variant="outline"
            size="sm"
            onClick={handleDownloadLog}
            disabled={isLoading || !job.log_file_path}
            title="Download log file"
          >
            Download Log
          </Button>
          <Button
            type="button"
            variant="ghost"
            size="icon-sm"
            onClick={onClose}
            title="Close"
            aria-label="Close"
          >
            <X className="h-[18px] w-[18px]" />
          </Button>
        </div>
      </div>

      <div className="flex min-h-0 flex-1 flex-col px-5 py-4">
        <div className="mb-2 flex items-center justify-between">
          <span className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">
            Console Output
          </span>
          {job.status === 'running' && (
            <span className="text-[0.7rem] font-medium text-[var(--green)]">
              ● Live
            </span>
          )}
        </div>
        <pre
          ref={consoleRef}
          className="m-0 min-h-0 flex-1 overflow-auto whitespace-pre-wrap break-words rounded-lg border border-border bg-background p-3 font-mono text-xs leading-normal text-foreground"
        >
          {logs.length === 0 ? (
            <span className="italic text-muted-foreground">
              {job.status === 'running'
                ? 'Waiting for logs...'
                : 'No logs available'}
            </span>
          ) : (
            logs.join('\n')
          )}
        </pre>
      </div>

      <div
        role="presentation"
        onMouseDown={onMouseDown}
        className={cn(
          'absolute bottom-0 left-0 top-0 z-[1] w-1.5 cursor-col-resize hover:bg-accent/20',
          isDragging && 'bg-accent/20',
        )}
      />
    </aside>
  );
}
