// apps/fastvideo_studio/src/components/JobQueue.tsx
'use client';

import * as React from 'react';

import JobCard from '@/components/JobCard';
import { useStore } from '@/hooks/useStore';
import { getJobsList } from '@/lib/api';
import type { Job, JobType } from '@/lib/types';
import {
  activeJobStore,
  setActiveJob,
  setActiveJobId,
} from '@/stores/activeJob';
import { jobsRefreshStore } from '@/stores/jobsRefresh';

interface JobQueueProps {
  jobType: JobType;
  jobTypesForList?: JobType[];
}

export default function JobQueue({ jobType, jobTypesForList }: JobQueueProps) {
  const [jobs, setJobs] = React.useState<Job[]>([]);
  const { nonce } = useStore(jobsRefreshStore);
  const { activeJobId } = useStore(activeJobStore);

  // Stable primitive key so the memoized list below keeps its identity when an
  // inline array prop (e.g. ['finetuning', 'lora']) gets a fresh reference each
  // render, which would otherwise re-run the fetch effects needlessly.
  const typesKey = (jobTypesForList ?? [jobType]).join(',');
  const typesToFetch = React.useMemo<JobType[]>(
    () => jobTypesForList ?? [jobType],
    // eslint-disable-next-line react-hooks/exhaustive-deps
    [typesKey],
  );

  const fetchJobs = React.useCallback(async () => {
    try {
      if (typesToFetch.length === 1) {
        setJobs(await getJobsList(typesToFetch[0]));
      } else {
        const results = await Promise.all(
          typesToFetch.map((t) => getJobsList(t)),
        );
        setJobs(
          results
            .flat()
            .sort(
              (a, b) =>
                new Date(b.created_at ?? 0).getTime() -
                new Date(a.created_at ?? 0).getTime(),
            ),
        );
      }
    } catch (e) {
      console.error('Failed to fetch jobs:', e);
    }
  }, [typesKey]);

  // Keep the latest fetchJobs reachable from the polling interval without
  // tearing it down/recreating it on every fetchJobs identity change.
  const fetchJobsRef = React.useRef(fetchJobs);
  React.useEffect(() => {
    fetchJobsRef.current = fetchJobs;
  }, [fetchJobs]);

  // Initial fetch + refetch whenever an external refresh is triggered.
  React.useEffect(() => {
    fetchJobs();
  }, [fetchJobs, nonce]);

  // Poll every second while any job is running/pending; stop otherwise.
  const hasActive = jobs.some(
    (j) => j.status === 'running' || j.status === 'pending',
  );
  React.useEffect(() => {
    if (!hasActive) return;
    const interval = setInterval(() => fetchJobsRef.current(), 1000);
    return () => clearInterval(interval);
  }, [hasActive]);

  // Keep the active job in sync with the selected id, and void the selection
  // if its job disappeared (e.g. deleted). When nothing is selected, clear the
  // store at most once rather than writing null on every poll tick.
  React.useEffect(() => {
    if (!activeJobId) {
      if (activeJobStore.get().activeJob) setActiveJob(null);
      return;
    }
    const activeJob = jobs.find((j) => j.id === activeJobId) ?? null;
    setActiveJob(activeJob);
    if (!activeJob) setActiveJobId(null);
  }, [activeJobId, jobs]);

  const multiType = typesToFetch.length > 1;

  return (
    <main className="mx-auto flex w-full max-w-[850px] flex-col gap-6 px-4 pb-12">
      <section className="p-6">
        <div>
          {jobs.length === 0 ? (
            <p className="py-8 text-center text-muted-foreground">
              No {multiType ? 'jobs' : `${jobType} jobs`} yet. Create one above.
            </p>
          ) : (
            jobs.map((job) => (
              <JobCard key={job.id} job={job} onJobUpdated={fetchJobs} />
            ))
          )}
        </div>
      </section>
    </main>
  );
}

// ui/src/lib/components/JobQueue.svelte
<script lang="ts">
	import { onMount, onDestroy } from "svelte";
	import { getJobsList } from "$lib/api";
	import type { JobType } from "$lib/types";
	import type { Job } from "$lib/types";
	import JobCard from "./JobCard.svelte";
	import { activeJobId, setActiveJobId, setActiveJob } from "$lib/stores/activeJob";
	import { registerRefresh, triggerRefresh } from "$lib/stores/jobsRefresh";

	let { jobType }: { jobType: JobType } = $props();

	let jobs = $state<Job[]>([]);
	let interval: ReturnType<typeof setInterval> | null = null;

	const activeJob = $derived(
		$activeJobId ? jobs.find((j) => j.id === $activeJobId) ?? null : null,
	);

	$effect(() => {
		setActiveJob(activeJob);
		// Void active job ID if deleeted
		if ($activeJobId && !activeJob) setActiveJobId(null);
	});

	async function fetchJobs() {
		try {
			jobs = await getJobsList(jobType);
		} catch (e) {
			console.error("Failed to fetch jobs:", e);
		}
	}

	$effect(() => {
		const hasActive = jobs.some(
			(j) => j.status === "running" || j.status === "pending",
		);
		if (hasActive) {
			interval = setInterval(fetchJobs, 1000);
		} else if (interval) {
			clearInterval(interval);
			interval = null;
		}
		return () => {
			if (interval) clearInterval(interval);
		};
	});

	onMount(() => {
		fetchJobs();
		return registerRefresh(fetchJobs);
	});

	onDestroy(() => {
		if (interval) clearInterval(interval);
	});
</script>

<main class="main">
	<section class="card">
		<div id="jobs-container">
			{#if jobs.length === 0}
				<p class="placeholder">No {jobType} jobs yet. Create one above.</p>
			{:else}
				{#each jobs as job (job.id)}
					<JobCard {job} onJobUpdated={fetchJobs} />
				{/each}
			{/if}
		</div>
	</section>
</main>

<style>
	.main {
		max-width: 850px;
		margin: 0 auto;
		padding: 0 1rem 3rem;
		display: flex;
		flex-direction: column;
		gap: 1.5rem;
		width: 100%;
	}
	.card {
		padding: 1.5rem;
	}
	.placeholder {
		text-align: center;
		color: var(--text-dim);
		padding: 2rem 0;
	}
</style>
