// apps/fastvideo_studio/src/components/PrimarySidebar.tsx
'use client';

import * as React from 'react';
import Link from 'next/link';
import { usePathname } from 'next/navigation';

import { useResizable } from '@/hooks/useResizable';
import { cn } from '@/lib/utils';

const SIDEBAR_MIN_WIDTH = 100;
const SIDEBAR_MAX_WIDTH = 300;
const SIDEBAR_COLLAPSED_WIDTH = 0;
const SIDEBAR_COLLAPSED_VISIBLE_WIDTH = 60;

const JOB_ROUTES = [
  { href: '/inference', label: 'Inference' },
  { href: '/finetuning', label: 'Finetuning' },
  { href: '/distillation', label: 'Distillation' },
] as const;

const TAB_BASE =
  'block px-5 py-[0.65rem] text-left text-sm text-muted-foreground transition-colors hover:bg-accent/5 hover:text-foreground';
const TAB_ACTIVE = 'bg-accent/10 font-medium text-accent';

export default function PrimarySidebar({
  onWidthChange,
}: {
  onWidthChange?: (w: number) => void;
}) {
  const pathname = usePathname();
  const [width, setWidth] = React.useState(220);
  const [isCollapsed, setIsCollapsed] = React.useState(false);
  const [isDragging, setIsDragging] = React.useState(false);
  const [jobsOpen, setJobsOpen] = React.useState(true);

  const effectiveWidth = isCollapsed ? SIDEBAR_COLLAPSED_WIDTH : width;
  const layoutWidth = isCollapsed ? SIDEBAR_COLLAPSED_VISIBLE_WIDTH : width;
  const isJobsActive = JOB_ROUTES.some((r) => pathname === r.href);

  React.useEffect(() => {
    onWidthChange?.(layoutWidth);
  }, [layoutWidth, onWidthChange]);

  React.useEffect(() => {
    if (JOB_ROUTES.some((r) => pathname === r.href)) {
      setJobsOpen(true);
    }
  }, [pathname]);

  const { onMouseDown } = useResizable({
    edge: 'left',
    minWidth: SIDEBAR_MIN_WIDTH,
    maxWidth: SIDEBAR_MAX_WIDTH,
    getWidth: () => width,
    onWidth: setWidth,
    onDragChange: setIsDragging,
  });

  return (
    <aside
      className="fixed bottom-0 left-0 top-[var(--header-height)] z-50 flex max-h-[calc(100vh-var(--header-height))] shrink-0 flex-col border-r border-border bg-card"
      style={{ width: effectiveWidth }}
    >
      {!isCollapsed && (
        <nav className="flex flex-col py-2">
          <div className="flex flex-col">
            <button
              type="button"
              onClick={() => setJobsOpen((v) => !v)}
              aria-expanded={jobsOpen}
              aria-haspopup="true"
              className={cn(
                TAB_BASE,
                'flex w-full cursor-pointer items-center justify-between',
                isJobsActive && TAB_ACTIVE,
              )}
            >
              <span>Jobs</span>
              <svg
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                strokeWidth={2}
                className={cn(
                  'h-4 w-4 shrink-0 opacity-85 transition-transform',
                  jobsOpen && 'rotate-180',
                )}
              >
                <path d="M6 9l6 6 6-6" />
              </svg>
            </button>
            {jobsOpen && (
              <div className="mb-1 ml-4 flex flex-col border-l-2 border-border pl-2">
                {JOB_ROUTES.map((route) => (
                  <Link
                    key={route.href}
                    href={route.href}
                    className={cn(
                      TAB_BASE,
                      'px-4 py-2 text-[0.85rem]',
                      pathname === route.href && TAB_ACTIVE,
                    )}
                  >
                    {route.label}
                  </Link>
                ))}
              </div>
            )}
          </div>
          <Link
            href="/datasets"
            className={cn(TAB_BASE, pathname === '/datasets' && TAB_ACTIVE)}
          >
            Datasets
          </Link>
          <Link
            href="/gallery"
            className={cn(TAB_BASE, pathname === '/gallery' && TAB_ACTIVE)}
          >
            Gallery
          </Link>
          <Link
            href="/settings"
            className={cn(TAB_BASE, pathname === '/settings' && TAB_ACTIVE)}
          >
            Settings
          </Link>
        </nav>
      )}

      <div
        className={cn(
          'absolute bottom-0 p-2',
          isCollapsed ? '-right-[60px] top-0' : 'right-0',
        )}
      >
        <button
          type="button"
          onClick={() => setIsCollapsed((v) => !v)}
          title={isCollapsed ? 'Expand sidebar' : 'Collapse sidebar'}
          className={cn(
            'flex items-center justify-center rounded-lg text-muted-foreground transition-colors hover:bg-accent/10 hover:text-foreground',
            isCollapsed ? 'p-3' : 'p-2',
          )}
        >
          <svg
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth={2}
            className="h-[18px] w-[18px]"
          >
            <path d={isCollapsed ? 'M9 18l6-6-6-6' : 'M15 18l-6-6 6-6'} />
          </svg>
        </button>
      </div>

      {!isCollapsed && (
        <div
          role="presentation"
          onMouseDown={onMouseDown}
          className={cn(
            'absolute bottom-0 right-0 top-0 z-[1] w-1.5 cursor-col-resize hover:bg-accent/20',
            isDragging && 'bg-accent/20',
          )}
        />
      )}
    </aside>
  );
}

// ui/src/lib/components/PrimarySidebar.svelte
<script lang="ts">
	import { page } from "$app/stores";
	import { resizable } from "$lib/actions/resizable";

	const SIDEBAR_MIN_WIDTH = 100;
	const SIDEBAR_MAX_WIDTH = 300;
	const SIDEBAR_COLLAPSED_WIDTH = 0;
	const SIDEBAR_COLLAPSED_VISIBLE_WIDTH = 60;

	const JOB_ROUTES = [
		{ href: "/inference", label: "Inference" },
		{ href: "/finetuning", label: "Finetuning" },
		{ href: "/distillation", label: "Distillation" },
	] as const;

	let { onWidthChange }: { onWidthChange?: (w: number) => void } = $props();

	let width = $state(220);
	let isCollapsed = $state(false);
	let isDragging = $state(false);
	let jobsOpen = $state(true);

	const effectiveWidth = isCollapsed ? SIDEBAR_COLLAPSED_WIDTH : width;
	const layoutWidth = isCollapsed ? SIDEBAR_COLLAPSED_VISIBLE_WIDTH : width;
	const pathname = $derived($page.url.pathname);
	const isJobsActive = $derived(
		JOB_ROUTES.some((r) => pathname === r.href),
	);

	$effect(() => {
		onWidthChange?.(layoutWidth);
	});

	$effect(() => {
		if (JOB_ROUTES.some((r) => pathname === r.href)) {
			jobsOpen = true;
		}
	});

	const resizableOpts = $derived({
		edge: "left" as const,
		minWidth: SIDEBAR_MIN_WIDTH,
		maxWidth: SIDEBAR_MAX_WIDTH,
		getWidth: () => width,
		onWidth: (w: number) => (width = w),
		onDragChange: (dragging: boolean) => (isDragging = dragging),
	});

	function toggleCollapse() {
		isCollapsed = !isCollapsed;
	}

	function toggleJobs() {
		jobsOpen = !jobsOpen;
	}
</script>

<aside
	class="sidebar"
	class:collapsed={isCollapsed}
	style="width: {effectiveWidth}px"
>
	<nav class="tabs">
		<div class="jobsGroup">
			<button
				type="button"
				class="tab tabTrigger"
				class:tabActive={isJobsActive}
				onclick={toggleJobs}
				aria-expanded={jobsOpen}
				aria-haspopup="true"
			>
				<span>Jobs</span>
				<svg
					class="chevron"
					viewBox="0 0 24 24"
					fill="none"
					stroke="currentColor"
					stroke-width="2"
					class:rotated={jobsOpen}
				>
					<path d="M6 9l6 6 6-6" />
				</svg>
			</button>
			{#if jobsOpen}
				<div class="jobsSubnav">
					{#each JOB_ROUTES as route}
						<a
							href={route.href}
							class="tab subTab"
							class:tabActive={pathname === route.href}
						>
							{route.label}
						</a>
					{/each}
				</div>
			{/if}
		</div>
		<a href="/datasets" class="tab" class:tabActive={pathname === "/datasets"}>Datasets</a>
		<a href="/settings" class="tab" class:tabActive={pathname === "/settings"}>Settings</a>
	</nav>
	<div class="collapseFooter">
		<button
			type="button"
			class="collapseBtn"
			onclick={toggleCollapse}
			title={isCollapsed ? "Expand sidebar" : "Collapse sidebar"}
		>
			{#if isCollapsed}
				<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
					<path d="M9 18l6-6-6-6" />
				</svg>
			{:else}
				<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
					<path d="M15 18l-6-6 6-6" />
				</svg>
			{/if}
		</button>
	</div>
	{#if !isCollapsed}
		<div
			class="resizeHandle"
			class:resizeHandleActive={isDragging}
			use:resizable={resizableOpts}
			role="presentation"
		></div>
	{/if}
</aside>

<style>
	.sidebar {
		position: fixed;
		top: var(--header-height);
		left: 0;
		bottom: 0;
		display: flex;
		flex-direction: column;
		max-height: calc(100vh - var(--header-height));
		background: var(--surface);
		border-right: 1px solid var(--border);
		flex-shrink: 0;
		z-index: 50;
	}
	.resizeHandle {
		position: absolute;
		top: 0;
		right: 0;
		width: 6px;
		bottom: 0;
		cursor: col-resize;
		z-index: 1;
	}
	.resizeHandle:hover,
	.resizeHandleActive {
		background: rgba(99, 102, 241, 0.2);
	}
	.resizeHandle::after {
		content: "";
		position: absolute;
		top: 50%;
		left: 50%;
		transform: translate(-50%, -50%);
		width: 2px;
		height: 24px;
		background: var(--border);
		border-radius: 1px;
		opacity: 0;
		transition: opacity 0.15s;
	}
	.resizeHandle:hover::after,
	.resizeHandleActive::after {
		opacity: 1;
	}
	.collapseFooter {
		padding: 0.5rem;
		position: absolute;
		bottom: 0;
		right: 0;
	}
	.collapseBtn {
		display: flex;
		align-items: center;
		justify-content: center;
		width: 100%;
		padding: 0.5rem;
		background: none;
		border: none;
		color: var(--text-dim);
		cursor: pointer;
		border-radius: var(--radius);
		font-family: inherit;
		transition: color 0.15s, background 0.15s;
	}
	.collapseBtn:hover {
		color: var(--text);
		background: rgba(99, 102, 241, 0.08);
	}
	.collapseBtn svg {
		width: 18px;
		height: 18px;
	}
	.collapsed .tabs {
		display: none;
	}
	.collapsed .collapseFooter {
		border-top: none;
		top: 0;
		right: -60px;
	}
	.collapsed .collapseBtn {
		width: auto;
		padding: 0.75rem;
	}
	.tabs {
		display: flex;
		flex-direction: column;
		padding: 0.5rem 0;
	}
	.tab {
		display: block;
		padding: 0.65rem 1.25rem;
		font-size: 0.9rem;
		color: var(--text-dim);
		text-decoration: none;
		border: none;
		background: none;
		text-align: left;
		font-family: inherit;
		transition: color 0.15s, background 0.15s;
	}
	.tab:hover {
		color: var(--text);
		background: rgba(99, 102, 241, 0.08);
	}
	.tabActive {
		color: var(--accent);
		font-weight: 500;
		background: rgba(99, 102, 241, 0.12);
	}
	.jobsGroup {
		display: flex;
		flex-direction: column;
		gap: 0;
	}
	.tabTrigger {
		display: flex;
		align-items: center;
		justify-content: space-between;
		width: 100%;
		cursor: pointer;
	}
	.tabTrigger .chevron {
		width: 16px;
		height: 16px;
		flex-shrink: 0;
		opacity: 0.85;
		transition: transform 0.2s;
	}
	.tabTrigger .chevron.rotated {
		transform: rotate(180deg);
	}
	.jobsSubnav {
		display: flex;
		flex-direction: column;
		padding-left: 0.5rem;
		border-left: 2px solid var(--border);
		margin-left: 1rem;
		margin-bottom: 0.25rem;
	}
	.subTab {
		padding: 0.5rem 1rem;
		font-size: 0.85rem;
	}
</style>
