// ui/src/components/PrimarySidebar.tsx
'use client';

import { useCallback, useEffect, useRef, useState } from "react";
import primarySidebarStyles from "./styles/PrimarySidebar.module.css";

const SIDEBAR_MIN_WIDTH = 100;
const SIDEBAR_MAX_WIDTH = 300;
const SIDEBAR_COLLAPSED_WIDTH = 0;
const SIDEBAR_COLLAPSED_VISIBLE_WIDTH = 60; /* collapse button width */

export type SidebarTab =
  | "inference"
  | "finetuning"
  | "distillation"
  | "lora"
  | "datasets"
  | "settings";

interface PrimarySidebarProps {
  activeTab: SidebarTab;
  onTabChange: (tab: SidebarTab) => void;
  onWidthChange?: (width: number) => void;
}

function CollapseIcon() {
  return (
    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
      <path d="M15 18l-6-6 6-6" />
    </svg>
  );
}

function ExpandIcon() {
  return (
    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
      <path d="M9 18l6-6-6-6" />
    </svg>
  );
}

export default function PrimarySidebar({
  activeTab,
  onTabChange,
  onWidthChange,
}: PrimarySidebarProps) {
  const [width, setWidth] = useState(220);
  const [isCollapsed, setIsCollapsed] = useState(false);
  const [isDragging, setIsDragging] = useState(false);
  const dragStartRef = useRef({ x: 0, width: 0 });

  const effectiveWidth = isCollapsed ? SIDEBAR_COLLAPSED_WIDTH : width;
  const layoutWidth = isCollapsed ? SIDEBAR_COLLAPSED_VISIBLE_WIDTH : width;

  useEffect(() => {
    onWidthChange?.(layoutWidth);
  }, [layoutWidth, onWidthChange]);

  const handleMouseDown = useCallback(
    (e: React.MouseEvent) => {
      e.preventDefault();
      dragStartRef.current = { x: e.clientX, width };
      setIsDragging(true);
    },
    [width]
  );

  useEffect(() => {
    if (!isDragging) return;

    const handleMouseMove = (e: MouseEvent) => {
      const { x, width: startWidth } = dragStartRef.current;
      const delta = e.clientX - x;
      const newWidth = Math.min(
        SIDEBAR_MAX_WIDTH,
        Math.max(SIDEBAR_MIN_WIDTH, startWidth + delta)
      );
      setWidth(newWidth);
    };

    const handleMouseUp = () => {
      setIsDragging(false);
    };

    document.body.style.cursor = "col-resize";
    document.body.style.userSelect = "none";
    document.addEventListener("mousemove", handleMouseMove);
    document.addEventListener("mouseup", handleMouseUp);

    return () => {
      document.body.style.cursor = "";
      document.body.style.userSelect = "";
      document.removeEventListener("mousemove", handleMouseMove);
      document.removeEventListener("mouseup", handleMouseUp);
    };
  }, [isDragging]);

  const toggleCollapse = useCallback(() => {
    setIsCollapsed((prev) => !prev);
  }, []);

  return (
    <aside
      className={`${primarySidebarStyles.sidebar} ${
        isCollapsed ? primarySidebarStyles.collapsed : ""
      }`}
      style={{ width: effectiveWidth }}
    >
      <nav className={primarySidebarStyles.tabs}>
        <button
          type="button"
          className={`${primarySidebarStyles.tab} ${
            activeTab === "inference" ? primarySidebarStyles.tabActive : ""
          }`}
          onClick={() => onTabChange("inference")}
        >
          Inference
        </button>
        <button
          type="button"
          className={`${primarySidebarStyles.tab} ${
            activeTab === "finetuning" ? primarySidebarStyles.tabActive : ""
          }`}
          onClick={() => onTabChange("finetuning")}
        >
          Finetuning
        </button>
        <button
          type="button"
          className={`${primarySidebarStyles.tab} ${
            activeTab === "distillation" ? primarySidebarStyles.tabActive : ""
          }`}
          onClick={() => onTabChange("distillation")}
        >
          Distillation
        </button>
        <button
          type="button"
          className={`${primarySidebarStyles.tab} ${
            activeTab === "lora" ? primarySidebarStyles.tabActive : ""
          }`}
          onClick={() => onTabChange("lora")}
        >
          LoRA
        </button>
        <button
          type="button"
          className={`${primarySidebarStyles.tab} ${
            activeTab === "datasets" ? primarySidebarStyles.tabActive : ""
          }`}
          onClick={() => onTabChange("datasets")}
        >
          Datasets
        </button>
        <button
          type="button"
          className={`${primarySidebarStyles.tab} ${
            activeTab === "settings" ? primarySidebarStyles.tabActive : ""
          }`}
          onClick={() => onTabChange("settings")}
        >
          Settings
        </button>
      </nav>
      <div className={primarySidebarStyles.collapseFooter}>
        <button
          type="button"
          className={primarySidebarStyles.collapseBtn}
          onClick={toggleCollapse}
          title={isCollapsed ? "Expand sidebar" : "Collapse sidebar"}
        >
          {isCollapsed ? <ExpandIcon /> : <CollapseIcon />}
        </button>
      </div>
      {!isCollapsed && (
        <div
          className={`${primarySidebarStyles.resizeHandle} ${
            isDragging ? primarySidebarStyles.resizeHandleActive : ""
          }`}
          onMouseDown={handleMouseDown}
        />
      )}
    </aside>
  );
}

// ui/src/lib/components/PrimarySidebar.svelte
<script lang="ts">
	import { page } from "$app/stores";
	import { resizable } from "$lib/actions/resizable";

	const SIDEBAR_MIN_WIDTH = 100;
	const SIDEBAR_MAX_WIDTH = 300;
	const SIDEBAR_COLLAPSED_WIDTH = 0;
	const SIDEBAR_COLLAPSED_VISIBLE_WIDTH = 60;

	let { onWidthChange }: { onWidthChange?: (w: number) => void } = $props();

	let width = $state(220);
	let isCollapsed = $state(false);
	let isDragging = $state(false);

	const effectiveWidth = isCollapsed ? SIDEBAR_COLLAPSED_WIDTH : width;
	const layoutWidth = isCollapsed ? SIDEBAR_COLLAPSED_VISIBLE_WIDTH : width;

	$effect(() => {
		onWidthChange?.(layoutWidth);
	});

	const resizableOpts = $derived({
		edge: "left" as const,
		minWidth: SIDEBAR_MIN_WIDTH,
		maxWidth: SIDEBAR_MAX_WIDTH,
		getWidth: () => width,
		onWidth: (w: number) => (width = w),
		onDragChange: (dragging: boolean) => (isDragging = dragging),
	});

	function toggleCollapse() {
		isCollapsed = !isCollapsed;
	}
</script>

<aside
	class="sidebar"
	class:collapsed={isCollapsed}
	style="width: {effectiveWidth}px"
>
	<nav class="tabs">
		<a href="/inference" class="tab" class:tabActive={$page.url.pathname === "/inference"}>Inference</a>
		<a href="/finetuning" class="tab" class:tabActive={$page.url.pathname === "/finetuning"}>Finetuning</a>
		<a href="/distillation" class="tab" class:tabActive={$page.url.pathname === "/distillation"}>Distillation</a>
		<a href="/lora" class="tab" class:tabActive={$page.url.pathname === "/lora"}>LoRA</a>
		<a href="/datasets" class="tab" class:tabActive={$page.url.pathname === "/datasets"}>Datasets</a>
		<a href="/settings" class="tab" class:tabActive={$page.url.pathname === "/settings"}>Settings</a>
	</nav>
	<div class="collapseFooter">
		<button
			type="button"
			class="collapseBtn"
			onclick={toggleCollapse}
			title={isCollapsed ? "Expand sidebar" : "Collapse sidebar"}
		>
			{#if isCollapsed}
				<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
					<path d="M9 18l6-6-6-6" />
				</svg>
			{:else}
				<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
					<path d="M15 18l-6-6 6-6" />
				</svg>
			{/if}
		</button>
	</div>
	{#if !isCollapsed}
		<div
			class="resizeHandle"
			class:resizeHandleActive={isDragging}
			use:resizable={resizableOpts}
			role="presentation"
		></div>
	{/if}
</aside>

<style>
	.sidebar {
		position: fixed;
		top: var(--header-height);
		left: 0;
		bottom: 0;
		display: flex;
		flex-direction: column;
		max-height: calc(100vh - var(--header-height));
		background: var(--surface);
		border-right: 1px solid var(--border);
		flex-shrink: 0;
		z-index: 50;
	}
	.resizeHandle {
		position: absolute;
		top: 0;
		right: 0;
		width: 6px;
		bottom: 0;
		cursor: col-resize;
		z-index: 1;
	}
	.resizeHandle:hover,
	.resizeHandleActive {
		background: rgba(99, 102, 241, 0.2);
	}
	.resizeHandle::after {
		content: "";
		position: absolute;
		top: 50%;
		left: 50%;
		transform: translate(-50%, -50%);
		width: 2px;
		height: 24px;
		background: var(--border);
		border-radius: 1px;
		opacity: 0;
		transition: opacity 0.15s;
	}
	.resizeHandle:hover::after,
	.resizeHandleActive::after {
		opacity: 1;
	}
	.collapseFooter {
		padding: 0.5rem;
		position: absolute;
		bottom: 0;
		right: 0;
	}
	.collapseBtn {
		display: flex;
		align-items: center;
		justify-content: center;
		width: 100%;
		padding: 0.5rem;
		background: none;
		border: none;
		color: var(--text-dim);
		cursor: pointer;
		border-radius: var(--radius);
		font-family: inherit;
		transition: color 0.15s, background 0.15s;
	}
	.collapseBtn:hover {
		color: var(--text);
		background: rgba(99, 102, 241, 0.08);
	}
	.collapseBtn svg {
		width: 18px;
		height: 18px;
	}
	.collapsed .tabs {
		display: none;
	}
	.collapsed .collapseFooter {
		border-top: none;
		top: 0;
		right: -60px;
	}
	.collapsed .collapseBtn {
		width: auto;
		padding: 0.75rem;
	}
	.tabs {
		display: flex;
		flex-direction: column;
		padding: 0.5rem 0;
	}
	.tab {
		display: block;
		padding: 0.65rem 1.25rem;
		font-size: 0.9rem;
		color: var(--text-dim);
		text-decoration: none;
		border: none;
		background: none;
		text-align: left;
		font-family: inherit;
		transition: color 0.15s, background 0.15s;
	}
	.tab:hover {
		color: var(--text);
		background: rgba(99, 102, 241, 0.08);
	}
	.tabActive {
		color: var(--accent);
		font-weight: 500;
		background: rgba(99, 102, 241, 0.12);
	}
</style>
