// ui/src/lib/components/CreateDatasetModal.svelte
<script lang="ts">
	import { createDataset, uploadRawDataset } from "$lib/api";
	import UploadZone from "./UploadZone.svelte";
	import TabSwitch from "./TabSwitch.svelte";
	import {
		parseVideos2Caption,
		parseVideosCaptionsTxt,
		parseCaptionCsv,
	} from "$lib/captionParsing";

	const ALLOWED_VIDEO_EXT = ".mp4,.webm,.avi,.mov,.mkv";

	let {
		isOpen,
		onClose,
		onSuccess,
	}: {
		isOpen: boolean;
		onClose: () => void;
		onSuccess: () => void;
	} = $props();

	let name = $state("");
	let isSubmitting = $state(false);
	let rawPath = $state("");
	let fileNames = $state<string[]>([]);
	let isUploading = $state(false);
	let validationError = $state<string | null>(null);
	let captionFormat = $state<"json" | "txt" | "csv">("json");
	let captionMap = $state<Record<string, string> | null>(null);
	let captionFileName = $state<string | null>(null);
	let videosTxtLines = $state<string[] | null>(null);
	let videosTxtFileName = $state<string | null>(null);
	let captionsTxtLines = $state<string[] | null>(null);
	let captionsTxtFileName = $state<string | null>(null);

	$effect(() => {
		if (captionFormat === "txt" && captionsTxtLines && fileNames.length > 0) {
			const hasVideosTxt =
				videosTxtLines &&
				videosTxtLines.length > 0 &&
				videosTxtLines.some((s) => s.trim());
			if (hasVideosTxt && videosTxtLines) {
				const { error } = parseVideosCaptionsTxt(
					videosTxtLines,
					captionsTxtLines,
					fileNames,
				);
				validationError = error;
			} else {
				validationError = null;
			}
		}
	});

	const txtCaptionMap = $derived.by(() => {
		if (!captionsTxtLines || fileNames.length === 0) return null;
		const { captions, error } = parseVideosCaptionsTxt(
			videosTxtLines ?? null,
			captionsTxtLines,
			fileNames,
		);
		if (error) return null;
		return Object.keys(captions).length > 0 ? captions : null;
	});

	const effectiveCaptionMap = $derived(
		captionFormat === "txt" ? txtCaptionMap : captionMap,
	);

	$effect(() => {
		if (!isOpen) return;
		function onKey(e: KeyboardEvent) {
			if (e.key === "Escape" && !isSubmitting) handleClose();
		}
		document.addEventListener("keydown", onKey);
		return () => document.removeEventListener("keydown", onKey);
	});

	function handleClose() {
		if (isSubmitting) return;
		name = "";
		rawPath = "";
		fileNames = [];
		validationError = null;
		captionFormat = "json";
		captionMap = null;
		captionFileName = null;
		videosTxtLines = null;
		videosTxtFileName = null;
		captionsTxtLines = null;
		captionsTxtFileName = null;
		onClose();
	}

	async function handleCaptionJsonChange(files: File[]) {
		validationError = null;
		captionMap = null;
		captionFileName = null;
		if (files.length === 0) return;
		const file = files[0];
		try {
			const text = await file.text();
			const uploaded = fileNames.length > 0 ? fileNames : [];
			const { captions, error } = parseVideos2Caption(text, uploaded);
			if (error) {
				validationError = error;
				return;
			}
			captionMap = captions;
			captionFileName = file.name;
		} catch {
			validationError = "Could not read the file.";
		}
	}

	async function handleVideosTxtChange(files: File[]) {
		validationError = null;
		videosTxtLines = null;
		videosTxtFileName = null;
		if (files.length === 0) return;
		try {
			const text = await files[0].text();
			videosTxtLines = text.split(/\r?\n/).map((s) => s.trim());
			videosTxtFileName = files[0].name;
			if (captionsTxtLines && fileNames.length > 0) {
				const { error } = parseVideosCaptionsTxt(
					videosTxtLines,
					captionsTxtLines,
					fileNames,
				);
				if (error) validationError = error;
			}
		} catch {
			validationError = "Could not read videos.txt.";
		}
	}

	async function handleCaptionsTxtChange(files: File[]) {
		validationError = null;
		captionsTxtLines = null;
		captionsTxtFileName = null;
		if (files.length === 0) return;
		try {
			const text = await files[0].text();
			captionsTxtLines = text.split(/\r?\n/).map((s) => s.trim());
			captionsTxtFileName = files[0].name;
			if (videosTxtLines && fileNames.length > 0) {
				const { error } = parseVideosCaptionsTxt(
					videosTxtLines,
					captionsTxtLines,
					fileNames,
				);
				if (error) validationError = error;
			}
		} catch {
			validationError = "Could not read captions.txt.";
		}
	}

	async function handleCaptionCsvChange(files: File[]) {
		validationError = null;
		captionMap = null;
		captionFileName = null;
		if (files.length === 0) return;
		const file = files[0];
		try {
			const text = await file.text();
			const uploaded = fileNames.length > 0 ? fileNames : [];
			const { captions, error } = parseCaptionCsv(text, uploaded);
			if (error) {
				validationError = error;
				return;
			}
			captionMap = captions;
			captionFileName = file.name;
		} catch {
			validationError = "Could not read the file.";
		}
	}

	function handleCaptionFormatChange(format: string) {
		captionFormat = format as "json" | "txt" | "csv";
		validationError = null;
		captionMap = null;
		captionFileName = null;
		videosTxtLines = null;
		videosTxtFileName = null;
		captionsTxtLines = null;
		captionsTxtFileName = null;
	}

	async function handleMediaChange(files: File[]) {
		validationError = null;
		if (files.length === 0) {
			rawPath = "";
			fileNames = [];
			return;
		}
		isUploading = true;
		try {
			const res = await uploadRawDataset(files);
			rawPath = res.path;
			fileNames = res.file_names;
			if (res.file_names.length === 0) {
				validationError = `No video files found. Allowed: ${ALLOWED_VIDEO_EXT}`;
			}
		} catch (err) {
			rawPath = "";
			fileNames = [];
			validationError =
				err instanceof Error ? err.message : "Upload failed";
		} finally {
			isUploading = false;
		}
	}

	async function handleSubmit(e: SubmitEvent) {
		e.preventDefault();
		validationError = null;
		if (!name.trim()) return;
		if (!rawPath || fileNames.length === 0) {
			validationError = "No data was found. Upload at least one video.";
			return;
		}
		if (captionFormat === "json" || captionFormat === "csv") {
			if (captionFileName && !captionMap) {
				validationError =
					"Caption file has errors. Fix or remove it before creating the dataset.";
				return;
			}
		} else if (captionFormat === "txt") {
			if (videosTxtFileName || captionsTxtFileName) {
				if (!captionsTxtFileName) {
					validationError = "Upload captions.txt to use TXT captions.";
					return;
				}
				if (validationError) return;
			}
		}

		const finalCaptionMap =
			effectiveCaptionMap && Object.keys(effectiveCaptionMap).length > 0
				? effectiveCaptionMap
				: null;
		if (finalCaptionMap) {
			const missing = fileNames.filter((fn) => !(fn in finalCaptionMap));
			if (missing.length > 0) {
				const list =
					missing.length <= 5
						? missing.join(", ")
						: `${missing.slice(0, 5).join(", ")} and ${missing.length - 5} more`;
				const ok = confirm(
					`The caption file does not include captions for ${missing.length} video(s): ${list}. They will get empty captions. Continue?`,
				);
				if (!ok) return;
			}
		}

		isSubmitting = true;
		try {
			await createDataset({
				name: name.trim(),
				upload_path: rawPath,
				file_names: fileNames,
				...(finalCaptionMap ? { captions: finalCaptionMap } : {}),
			});
			onSuccess();
			handleClose();
		} catch (err) {
			validationError =
				err instanceof Error ? err.message : "Failed to create dataset";
		} finally {
			isSubmitting = false;
		}
	}
</script>

{#if isOpen}
	<div class="modal" data-modal>
		<div class="modalBackdrop" onclick={handleClose} role="presentation"></div>
		<div class="modalContent modalForm">
			<button
				class="modalClose"
				onclick={handleClose}
				disabled={isSubmitting}
				aria-label="Close"
			>
				×
			</button>
			<div class="card">
				<h2>Add Dataset — Raw</h2>
				<form onsubmit={handleSubmit} autocomplete="off">
					<div class="formRow">
						<label for="add-dataset-name">Name</label>
						<input
							id="add-dataset-name"
							type="text"
							bind:value={name}
							placeholder="My dataset"
							required
							disabled={isSubmitting}
						/>
					</div>
					<div class="formRow">
						<label>Videos</label>
						<UploadZone
							label="Upload video files"
							hint="Select files or a folder (.mp4, .webm, .avi, .mov, .mkv)"
							accept={ALLOWED_VIDEO_EXT}
							multiple={true}
							directory={true}
							allowBothFileAndDirectory={true}
							value={rawPath}
							fileName={fileNames.length > 0 ? `${fileNames.length} file(s)` : undefined}
							onFileChange={handleMediaChange}
							onClear={() => {
								rawPath = "";
								fileNames = [];
								captionMap = null;
								captionFileName = null;
								validationError = null;
							}}
							disabled={isSubmitting}
							uploading={isUploading}
						/>
					</div>
					<div class="formRow">
						<div class="captionRow">
							<label>Captions (optional)</label>
							<TabSwitch
								options={[
									{ id: "json", label: "JSON" },
									{ id: "txt", label: "TXT" },
									{ id: "csv", label: "CSV" },
								]}
								value={captionFormat}
								onChange={handleCaptionFormatChange}
								disabled={isSubmitting}
							/>
						</div>
						{#if captionFormat === "json"}
							<UploadZone
								label="Upload videos2caption.json"
								hint={'Array of { path, cap } or object mapping file names to captions'}
								accept=".json,application/json"
								value={captionFileName ? "1" : ""}
								fileName={captionFileName ?? undefined}
								onFileChange={handleCaptionJsonChange}
								onClear={() => {
									captionMap = null;
									captionFileName = null;
									validationError = null;
								}}
								disabled={isSubmitting}
							/>
						{:else if captionFormat === "txt"}
							<div class="twoCol">
								<UploadZone
									label="Upload videos.txt (optional)"
									hint="One video path per line, or leave empty to match captions to videos in alphabetical order"
									accept=".txt,text/plain"
									value={videosTxtFileName ? "1" : ""}
									fileName={videosTxtFileName ?? undefined}
									onFileChange={handleVideosTxtChange}
									onClear={() => {
										videosTxtLines = null;
										videosTxtFileName = null;
										validationError = null;
									}}
									disabled={isSubmitting}
								/>
								<UploadZone
									label="Upload captions.txt"
									hint="One caption per line (same order as videos.txt or alphabetical)"
									accept=".txt,text/plain"
									value={captionsTxtFileName ? "1" : ""}
									fileName={captionsTxtFileName ?? undefined}
									onFileChange={handleCaptionsTxtChange}
									onClear={() => {
										captionsTxtLines = null;
										captionsTxtFileName = null;
										validationError = null;
									}}
									disabled={isSubmitting}
								/>
							</div>
						{:else}
							<UploadZone
								label="Upload captions CSV"
								hint="Header: video_name, caption"
								accept=".csv,text/csv"
								value={captionFileName ? "1" : ""}
								fileName={captionFileName ?? undefined}
								onFileChange={handleCaptionCsvChange}
								onClear={() => {
									captionMap = null;
									captionFileName = null;
									validationError = null;
								}}
								disabled={isSubmitting}
							/>
						{/if}
					</div>
					{#if validationError}
						<p class="validationError">{validationError}</p>
					{/if}
					<button type="submit" class="btn btnPrimary" disabled={isSubmitting}>
						{isSubmitting ? "Creating…" : "Create Dataset"}
					</button>
				</form>
			</div>
		</div>
	</div>
{/if}

<style>
	.modal {
		position: fixed;
		inset: 0;
		z-index: 1000;
		display: flex;
		align-items: center;
		justify-content: center;
	}
	.modalBackdrop {
		position: absolute;
		inset: 0;
		background: rgba(0, 0, 0, 0.7);
	}
	.modalContent {
		position: relative;
		z-index: 1;
		max-width: 90vw;
		max-height: 90vh;
		border-radius: var(--radius);
		overflow: hidden;
		background: var(--surface);
		border: 1px solid var(--border);
		padding: 0;
		max-width: 850px;
		width: 90vw;
		max-height: 90vh;
		overflow-y: auto;
	}
	.modalClose {
		position: absolute;
		top: 0.5rem;
		right: 0.75rem;
		background: none;
		border: none;
		color: var(--text);
		font-size: 1.6rem;
		cursor: pointer;
		z-index: 2;
	}
	.card {
		padding: 1.5rem;
	}
	.card h2 {
		font-size: 1.15rem;
		margin-bottom: 1rem;
	}
	.formRow {
		display: flex;
		flex-direction: column;
		gap: 0.35rem;
		margin-bottom: 0.85rem;
	}
	.formRow label {
		font-size: 0.8rem;
		color: var(--text-dim);
	}
	.captionRow {
		display: flex;
		align-items: center;
		gap: 1rem;
		flex-wrap: wrap;
		margin-bottom: 0.35rem;
	}
	.captionRow label {
		margin-bottom: 0;
	}
	.twoCol {
		display: flex;
		gap: 15px;
		flex-wrap: wrap;
	}
	.validationError {
		color: var(--red);
		font-size: 0.85rem;
		margin-bottom: 0.5rem;
	}
	.btn {
		cursor: pointer;
		border: none;
		border-radius: var(--radius);
		font-family: inherit;
		font-weight: 600;
		padding: 0.55rem 1.2rem;
	}
	.btnPrimary {
		background: var(--accent);
		color: #fff;
	}
	.btn:disabled {
		opacity: 0.5;
		cursor: not-allowed;
	}
</style>

// ui/src/components/CreateDatasetModal.tsx
"use client";

import { createDataset, uploadRawDataset } from "@/lib/api";
import { useEffect, useMemo, useState } from "react";
import modalStyles from "./styles/Modal.module.css";
import formStyles from "./styles/Form.module.css";
import cardStyles from "./styles/Card.module.css";
import buttonStyles from "./styles/Button.module.css";
import UploadZone from "./UploadZone";
import TabSwitch from "./TabSwitch";

const ALLOWED_VIDEO_EXT = ".mp4,.webm,.avi,.mov,.mkv";

/** Parse and validate videos2caption.json. Returns { captions, error }. */
function parseVideos2Caption(
	text: string,
	uploadedFileNames: string[],
): { captions: Record<string, string>; error: string | null } {
	let data: unknown;
	try {
		data = JSON.parse(text);
	} catch {
		return { captions: {}, error: "Invalid JSON in videos2caption.json." };
	}

	const captions: Record<string, string> = {};
	const uploadedSet = new Set(uploadedFileNames);

	if (Array.isArray(data)) {
		for (let i = 0; i < data.length; i++) {
			const entry = data[i];
			if (entry === null || typeof entry !== "object") {
				return {
					captions: {},
					error: `Invalid entry at index ${i}: must be an object with "path" and "cap".`,
				};
			}
			const path = (entry as Record<string, unknown>)["path"];
			const cap = (entry as Record<string, unknown>)["cap"];
			if (typeof path !== "string") {
				return {
					captions: {},
					error: `Invalid entry at index ${i}: "path" must be a string.`,
				};
			}
			let caption: string;
			if (typeof cap === "string") {
				caption = cap;
			} else if (
				Array.isArray(cap) &&
				cap.length > 0 &&
				typeof cap[0] === "string"
			) {
				caption = cap[0];
			} else {
				return {
					captions: {},
					error: `Invalid entry at index ${i}: "cap" must be a string or non-empty array of strings.`,
				};
			}
			captions[path] = caption;
		}
	} else if (
		data !== null &&
		typeof data === "object" &&
		!Array.isArray(data)
	) {
		const obj = data as Record<string, unknown>;
		for (const [key, value] of Object.entries(obj)) {
			if (typeof key !== "string" || typeof value !== "string") {
				return {
					captions: {},
					error: `Invalid entry for "${String(key)}": keys and values must be strings.`,
				};
			}
			captions[key] = value;
		}
	} else {
		return {
			captions: {},
			error: "videos2caption.json must be an array of { path, cap } or an object mapping file names to captions.",
		};
	}

	if (uploadedFileNames.length > 0) {
		const unknownRefs = Object.keys(captions).filter(
			(k) => !uploadedSet.has(k),
		);
		if (unknownRefs.length > 0) {
			return {
				captions: {},
				error: `videos2caption.json references file(s) not in the uploaded videos: ${unknownRefs.slice(0, 5).join(", ")}${unknownRefs.length > 5 ? "…" : ""}.`,
			};
		}
	}

	return { captions, error: null };
}

/**
 * Parse videos.txt + captions.txt: line i in videos = path, line i in captions = caption.
 * If videosLines is null/empty, map captions to uploaded file names in alphabetical order.
 */
function parseVideosCaptionsTxt(
	videosLines: string[] | null,
	captionsLines: string[],
	uploadedFileNames: string[],
): { captions: Record<string, string>; error: string | null } {
	const captions: Record<string, string> = {};
	const useAlphabetical =
		!videosLines ||
		videosLines.length === 0 ||
		videosLines.every((s) => !s.trim());
	const paths: string[] = useAlphabetical
		? [...uploadedFileNames].sort()
		: videosLines!.map((s) => s.trim()).filter(Boolean);
	const len = Math.min(paths.length, captionsLines.length);
	for (let i = 0; i < len; i++) {
		const path = paths[i];
		if (path) captions[path] = captionsLines[i].trim();
	}
	if (!useAlphabetical && uploadedFileNames.length > 0) {
		const uploadedSet = new Set(uploadedFileNames);
		const unknownRefs = Object.keys(captions).filter(
			(k) => !uploadedSet.has(k),
		);
		if (unknownRefs.length > 0) {
			return {
				captions: {},
				error: `videos.txt references file(s) not in the uploaded videos: ${unknownRefs.slice(0, 5).join(", ")}${unknownRefs.length > 5 ? "…" : ""}.`,
			};
		}
	}
	return { captions, error: null };
}

/** Parse CSV with video_name,caption columns. */
function parseCaptionCsv(
	text: string,
	uploadedFileNames: string[],
): { captions: Record<string, string>; error: string | null } {
	const lines = text.split(/\r?\n/).filter((s) => s.trim());
	if (lines.length < 2) {
		return {
			captions: {},
			error: "CSV must have a header row and at least one data row.",
		};
	}
	const headerParts = parseCsvLine(lines[0]).map((s) =>
		s.trim().toLowerCase(),
	);
	const vidIdx = headerParts.includes("video_name")
		? headerParts.indexOf("video_name")
		: 0;
	const capIdx = headerParts.includes("caption")
		? headerParts.indexOf("caption")
		: 1;
	const captions: Record<string, string> = {};
	for (let i = 1; i < lines.length; i++) {
		const row = parseCsvLine(lines[i]);
		const path = row[vidIdx]?.trim();
		const cap = row[capIdx]?.trim() ?? "";
		if (path) captions[path] = cap;
	}
	if (uploadedFileNames.length > 0) {
		const uploadedSet = new Set(uploadedFileNames);
		const unknownRefs = Object.keys(captions).filter(
			(k) => !uploadedSet.has(k),
		);
		if (unknownRefs.length > 0) {
			return {
				captions: {},
				error: `CSV references file(s) not in the uploaded videos: ${unknownRefs.slice(0, 5).join(", ")}${unknownRefs.length > 5 ? "…" : ""}.`,
			};
		}
	}
	return { captions, error: null };
}

function parseCsvLine(line: string): string[] {
	const out: string[] = [];
	let cur = "";
	let inQuotes = false;
	for (let i = 0; i < line.length; i++) {
		const c = line[i];
		if (c === '"') {
			if (inQuotes && line[i + 1] === '"') {
				cur += '"';
				i++;
			} else {
				inQuotes = !inQuotes;
			}
		} else if ((c === "," && !inQuotes) || c === "\n") {
			out.push(cur);
			cur = "";
		} else {
			cur += c;
		}
	}
	out.push(cur);
	return out;
}

interface CreateDatasetModalProps {
	isOpen: boolean;
	onClose: () => void;
	onSuccess: () => void;
}

export default function CreateDatasetModal({
	isOpen,
	onClose,
	onSuccess,
}: CreateDatasetModalProps) {
	const [name, setName] = useState("");
	const [isSubmitting, setIsSubmitting] = useState(false);
	const [rawPath, setRawPath] = useState("");
	const [fileNames, setFileNames] = useState<string[]>([]);
	const [isUploading, setIsUploading] = useState(false);
	const [validationError, setValidationError] = useState<string | null>(null);
	const [captionFormat, setCaptionFormat] = useState<"json" | "txt" | "csv">(
		"json",
	);
	const [captionMap, setCaptionMap] = useState<Record<string, string> | null>(
		null,
	);
	const [captionFileName, setCaptionFileName] = useState<string | null>(null);
	const [videosTxtLines, setVideosTxtLines] = useState<string[] | null>(null);
	const [videosTxtFileName, setVideosTxtFileName] = useState<string | null>(
		null,
	);
	const [captionsTxtLines, setCaptionsTxtLines] = useState<string[] | null>(
		null,
	);
	const [captionsTxtFileName, setCaptionsTxtFileName] = useState<
		string | null
	>(null);

	useEffect(() => {
		const handleEscape = (e: KeyboardEvent) => {
			if (e.key === "Escape" && isOpen && !isSubmitting) onClose();
		};
		if (isOpen) {
			document.addEventListener("keydown", handleEscape);
			return () => document.removeEventListener("keydown", handleEscape);
		}
	}, [isOpen, isSubmitting, onClose]);

	const handleClose = () => {
		if (!isSubmitting) {
			setName("");
			setRawPath("");
			setFileNames([]);
			setValidationError(null);
			setCaptionFormat("json");
			setCaptionMap(null);
			setCaptionFileName(null);
			setVideosTxtLines(null);
			setVideosTxtFileName(null);
			setCaptionsTxtLines(null);
			setCaptionsTxtFileName(null);
			onClose();
		}
	};

	const txtCaptionMap = useMemo(() => {
		if (!captionsTxtLines) return null;
		if (fileNames.length === 0) return null;
		const { captions, error } = parseVideosCaptionsTxt(
			videosTxtLines ?? null,
			captionsTxtLines,
			fileNames,
		);
		if (error) return null;
		return Object.keys(captions).length > 0 ? captions : null;
	}, [videosTxtLines, captionsTxtLines, fileNames]);

	useEffect(() => {
		if (
			captionFormat === "txt" &&
			captionsTxtLines &&
			fileNames.length > 0
		) {
			const hasVideosTxt =
				videosTxtLines &&
				videosTxtLines.length > 0 &&
				videosTxtLines.some((s) => s.trim());
			if (hasVideosTxt) {
				const { error } = parseVideosCaptionsTxt(
					videosTxtLines,
					captionsTxtLines,
					fileNames,
				);
				setValidationError(error ?? null);
			} else {
				setValidationError(null);
			}
		}
	}, [captionFormat, videosTxtLines, captionsTxtLines, fileNames]);

	const effectiveCaptionMap =
		captionFormat === "txt" ? txtCaptionMap : captionMap;

	const handleCaptionJsonChange = async (files: File[]) => {
		setValidationError(null);
		setCaptionMap(null);
		setCaptionFileName(null);
		if (files.length === 0) return;
		const file = files[0];
		let text: string;
		try {
			text = await file.text();
		} catch {
			setValidationError("Could not read the file.");
			return;
		}
		const uploaded = fileNames.length > 0 ? fileNames : [];
		const { captions, error } = parseVideos2Caption(text, uploaded);
		if (error) {
			setValidationError(error);
			return;
		}
		setCaptionMap(captions);
		setCaptionFileName(file.name);
	};

	const handleVideosTxtChange = async (files: File[]) => {
		setValidationError(null);
		setVideosTxtLines(null);
		setVideosTxtFileName(null);
		if (files.length === 0) return;
		try {
			const text = await files[0].text();
			const lines = text.split(/\r?\n/).map((s) => s.trim());
			setVideosTxtLines(lines);
			setVideosTxtFileName(files[0].name);
			if (captionsTxtLines && fileNames.length > 0) {
				const { error } = parseVideosCaptionsTxt(
					lines,
					captionsTxtLines,
					fileNames,
				);
				if (error) setValidationError(error);
			}
		} catch {
			setValidationError("Could not read videos.txt.");
		}
	};

	const handleCaptionsTxtChange = async (files: File[]) => {
		setValidationError(null);
		setCaptionsTxtLines(null);
		setCaptionsTxtFileName(null);
		if (files.length === 0) return;
		try {
			const text = await files[0].text();
			const lines = text.split(/\r?\n/).map((s) => s.trim());
			setCaptionsTxtLines(lines);
			setCaptionsTxtFileName(files[0].name);
			if (videosTxtLines && fileNames.length > 0) {
				const { error } = parseVideosCaptionsTxt(
					videosTxtLines,
					lines,
					fileNames,
				);
				if (error) setValidationError(error);
			}
		} catch {
			setValidationError("Could not read captions.txt.");
		}
	};

	const handleCaptionCsvChange = async (files: File[]) => {
		setValidationError(null);
		setCaptionMap(null);
		setCaptionFileName(null);
		if (files.length === 0) return;
		const file = files[0];
		let text: string;
		try {
			text = await file.text();
		} catch {
			setValidationError("Could not read the file.");
			return;
		}
		const uploaded = fileNames.length > 0 ? fileNames : [];
		const { captions, error } = parseCaptionCsv(text, uploaded);
		if (error) {
			setValidationError(error);
			return;
		}
		setCaptionMap(captions);
		setCaptionFileName(file.name);
	};

	const handleCaptionFormatChange = (format: string) => {
		setCaptionFormat(format as "json" | "txt" | "csv");
		setValidationError(null);
		setCaptionMap(null);
		setCaptionFileName(null);
		setVideosTxtLines(null);
		setVideosTxtFileName(null);
		setCaptionsTxtLines(null);
		setCaptionsTxtFileName(null);
	};

	const handleMediaChange = async (files: File[]) => {
		setValidationError(null);
		if (files.length === 0) {
			setRawPath("");
			setFileNames([]);
			return;
		}
		setIsUploading(true);
		try {
			const res = await uploadRawDataset(files);
			setRawPath(res.path);
			setFileNames(res.file_names);
			if (res.file_names.length === 0) {
				setValidationError(
					`No video files found. Allowed: ${ALLOWED_VIDEO_EXT}`,
				);
			}
		} catch (err) {
			console.error("Upload failed:", err);
			setRawPath("");
			setFileNames([]);
			setValidationError(
				err instanceof Error ? err.message : "Upload failed",
			);
		} finally {
			setIsUploading(false);
		}
	};

	const handleSubmit = async (e: React.FormEvent) => {
		e.preventDefault();
		setValidationError(null);
		if (!name.trim()) return;

		if (!rawPath || fileNames.length === 0) {
			setValidationError("No data was found. Upload at least one video.");
			return;
		}

		if (captionFormat === "json" || captionFormat === "csv") {
			if (captionFileName && !captionMap) {
				setValidationError(
					"Caption file has errors. Fix or remove it before creating the dataset.",
				);
				return;
			}
		} else if (
			captionFormat === "txt" &&
			(videosTxtFileName || captionsTxtFileName)
		) {
			if (!captionsTxtFileName) {
				setValidationError("Upload captions.txt to use TXT captions.");
				return;
			}
			if (validationError) return;
		}

		const finalCaptionMap =
			effectiveCaptionMap && Object.keys(effectiveCaptionMap).length > 0
				? effectiveCaptionMap
				: null;
		if (finalCaptionMap) {
			const missing = fileNames.filter((fn) => !(fn in finalCaptionMap));
			if (missing.length > 0) {
				const list =
					missing.length <= 5
						? missing.join(", ")
						: `${missing.slice(0, 5).join(", ")} and ${missing.length - 5} more`;
				const ok = window.confirm(
					`The caption file does not include captions for ${missing.length} video(s): ${list}. They will get empty captions. Continue?`,
				);
				if (!ok) return;
			}
		}

		setIsSubmitting(true);
		try {
			await createDataset({
				name: name.trim(),
				upload_path: rawPath,
				file_names: fileNames,
				...(finalCaptionMap ? { captions: finalCaptionMap } : {}),
			});
			onSuccess();
			handleClose();
		} catch (err) {
			console.error("Failed to create dataset:", err);
			setValidationError(
				err instanceof Error ? err.message : "Failed to create dataset",
			);
		} finally {
			setIsSubmitting(false);
		}
	};

	if (!isOpen) return null;

	return (
		<div className={modalStyles.modal} data-modal>
			<div className={modalStyles.modalBackdrop} onClick={handleClose} />
			<div
				className={`${modalStyles.modalContent} ${modalStyles.modalForm}`}
			>
				<button
					className={modalStyles.modalClose}
					onClick={handleClose}
					disabled={isSubmitting}
					aria-label="Close"
				>
					×
				</button>
				<div
					className={cardStyles.card}
					style={{ margin: 0, border: "none" }}
				>
					<h2>Add Dataset — Raw</h2>
					<form onSubmit={handleSubmit} autoComplete="off">
						<div className={formStyles.formRow}>
							<label htmlFor="add-dataset-name">Name</label>
							<input
								id="add-dataset-name"
								type="text"
								value={name}
								onChange={(e) => setName(e.target.value)}
								placeholder="My dataset"
								required
								disabled={isSubmitting}
							/>
						</div>
						<div className={formStyles.formRow}>
							<label>Videos</label>
							<UploadZone
								label="Upload video files"
								hint="Select files or a folder (.mp4, .webm, .avi, .mov, .mkv)"
								accept={ALLOWED_VIDEO_EXT}
								multiple
								directory
								allowBothFileAndDirectory
								value={rawPath}
								fileName={
									fileNames.length > 0
										? `${fileNames.length} file(s)`
										: undefined
								}
								onFileChange={handleMediaChange}
								onClear={() => {
									setRawPath("");
									setFileNames([]);
									setCaptionMap(null);
									setCaptionFileName(null);
									setValidationError(null);
								}}
								disabled={isSubmitting}
								uploading={isUploading}
							/>
						</div>
						<div className={formStyles.formRow}>
							<div
								style={{
									display: "flex",
									alignItems: "center",
									gap: "1rem",
									flexWrap: "wrap",
								}}
							>
								<label style={{ marginBottom: 0 }}>
									Captions (optional)
								</label>
								<TabSwitch
									options={[
										{ id: "json", label: "JSON" },
										{ id: "txt", label: "TXT" },
										{ id: "csv", label: "CSV" },
									]}
									value={captionFormat}
									onChange={handleCaptionFormatChange}
									disabled={isSubmitting}
								/>
							</div>
							{captionFormat === "json" && (
								<UploadZone
									label="Upload videos2caption.json"
									hint="Array of { path, cap } or object mapping file names to captions"
									accept=".json,application/json"
									value={captionFileName ? "1" : ""}
									fileName={captionFileName ?? undefined}
									onFileChange={handleCaptionJsonChange}
									onClear={() => {
										setCaptionMap(null);
										setCaptionFileName(null);
										setValidationError(null);
									}}
									disabled={isSubmitting}
								/>
							)}
							{captionFormat === "txt" && (
								<>
									<div
										className={formStyles.row}
										style={{ gap: "15px" }}
									>
										<UploadZone
											label="Upload videos.txt (optional)"
											hint="One video path per line, or leave empty to match captions to videos in alphabetical order"
											accept=".txt,text/plain"
											value={videosTxtFileName ? "1" : ""}
											fileName={
												videosTxtFileName ?? undefined
											}
											onFileChange={handleVideosTxtChange}
											onClear={() => {
												setVideosTxtLines(null);
												setVideosTxtFileName(null);
												setValidationError(null);
											}}
											disabled={isSubmitting}
										/>
										<UploadZone
											label="Upload captions.txt"
											hint="One caption per line (same order as videos.txt, or alphabetical video order if videos.txt is empty)"
											accept=".txt,text/plain"
											value={
												captionsTxtFileName ? "1" : ""
											}
											fileName={
												captionsTxtFileName ?? undefined
											}
											onFileChange={
												handleCaptionsTxtChange
											}
											onClear={() => {
												setCaptionsTxtLines(null);
												setCaptionsTxtFileName(null);
												setValidationError(null);
											}}
											disabled={isSubmitting}
										/>
									</div>
								</>
							)}
							{captionFormat === "csv" && (
								<UploadZone
									label="Upload captions.csv"
									hint="CSV with video_name and caption columns"
									accept=".csv,text/csv"
									value={captionFileName ? "1" : ""}
									fileName={captionFileName ?? undefined}
									onFileChange={handleCaptionCsvChange}
									onClear={() => {
										setCaptionMap(null);
										setCaptionFileName(null);
										setValidationError(null);
									}}
									disabled={isSubmitting}
								/>
							)}
						</div>
						{validationError && (
							<div
								className={formStyles.formRow}
								style={{
									color: "var(--red)",
									fontSize: "0.9rem",
								}}
							>
								{validationError}
							</div>
						)}
						<div
							className={formStyles.formRow}
							style={{ marginTop: "1rem" }}
						>
							<button
								type="submit"
								className={`${buttonStyles.btn} ${buttonStyles.btnPrimary}`}
								disabled={
									isSubmitting ||
									isUploading ||
									fileNames.length === 0 ||
									!name.trim()
								}
							>
								{isSubmitting ? "Creating…" : "Create Dataset"}
							</button>
						</div>
					</form>
				</div>
			</div>
		</div>
	);
}
